name: "Git Config"
description: "Configure git credentials, username etc."
branding:
  icon: "settings"
  color: "orange"
inputs:
  scope:
    description: Scope (global, local etc). Comma-separated values are allowed.
    default: global,local
  github-token:
    description: GitHub personal access token used as git credentials
runs:
  using: "node16"
  main: "dist/index.js"
  post: "dist/index.js"
